use uni_sports_platform
db.dropDatabase()
use uni_sports_platform
db.class.insertMany(
[{"Class_ID":600, "Days":"Monday", "Class_Cost":10, "Location":"Dungeons", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":97, "I_Name":"Snape", "A_HOGID":1, "A_Name":"Katie"},
 {"Class_ID":600, "Days":"Monday", "Class_Cost":10, "Location":"Dungeons", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":97, "I_Name":"Snape", "A_HOGID":11, "A_Name":"Harry"},
 {"Class_ID":600, "Days":"Monday", "Class_Cost":10, "Location":"Dungeons", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":97, "I_Name":"Snape", "A_HOGID":18, "A_Name":"Pavarti"},
 {"Class_ID":600, "Days":"Monday", "Class_Cost":10, "Location":"Dungeons", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":97, "I_Name":"Snape", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":601, "Days":"Tuesday", "Class_Cost":8, "Location":"Great Hall", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":1, "A_Name":"Katie"},
 {"Class_ID":601, "Days":"Tuesday", "Class_Cost":8, "Location":"Great Hall", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":2, "A_Name":"Fred"},
 {"Class_ID":601, "Days":"Tuesday", "Class_Cost":8, "Location":"Great Hall", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":6, "A_Name":"Luna"},
 {"Class_ID":601, "Days":"Tuesday", "Class_Cost":8, "Location":"Great Hall", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":15, "A_Name":"Dean"},
 {"Class_ID":601, "Days":"Tuesday", "Class_Cost":8, "Location":"Great Hall", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":17, "A_Name":"Seamus"},
 {"Class_ID":601, "Days":"Tuesday", "Class_Cost":8, "Location":"Great Hall", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":18, "A_Name":"Pavarti"},
 {"Class_ID":601, "Days":"Tuesday", "Class_Cost":8, "Location":"Great Hall", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":1, "A_Name":"Katie"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":3, "A_Name":"Fleur"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":5, "A_Name":"Goyle"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":7, "A_Name":"Charlie"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":8, "A_Name":"Penelope"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":10, "A_Name":"Bill"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":13, "A_Name":"Crabbe"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":14, "A_Name":"Viktor"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":16, "A_Name":"Angelina"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":17, "A_Name":"Seamus"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":22, "A_Name":"Draco"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":23, "A_Name":"Ron"},
 {"Class_ID":602, "Days":"Wednesday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":25, "A_Name":"Lavender"},
 {"Class_ID":603, "Days":"Thursday", "Class_Cost":20, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":91, "I_Name":"McGonnagall", "A_HOGID":18, "A_Name":"Pavarti"},
 {"Class_ID":603, "Days":"Thursday", "Class_Cost":20, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":91, "I_Name":"McGonnagall", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":603, "Days":"Thursday", "Class_Cost":20, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":91, "I_Name":"McGonnagall", "A_HOGID":27, "A_Name":"Cedric"},
 {"Class_ID":603, "Days":"Thursday", "Class_Cost":20, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":91, "I_Name":"McGonnagall", "A_HOGID":28, "A_Name":"Padma"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":2, "A_Name":"Fred"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":6, "A_Name":"Luna"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":9, "A_Name":"Ginny"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":11, "A_Name":"Harry"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":15, "A_Name":"Dean"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":19, "A_Name":"Cho"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":21, "A_Name":"Neville"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":23, "A_Name":"Ron"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":24, "A_Name":"Percy"},
 {"Class_ID":604, "Days":"Friday", "Class_Cost":10, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"09:00:00", "Class_End_Time":"10:00:00", "I_HOGID":93, "I_Name":"Sprout", "A_HOGID":26, "A_Name":"George"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":16, "A_Name":"Angelina"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":18, "A_Name":"Pavarti"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":25, "A_Name":"Lavender"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":27, "A_Name":"Cedric"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":28, "A_Name":"Padma"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":29, "A_Name":"Michael"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":30, "A_Name":"Ernie"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":31, "A_Name":"Hannah"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":32, "A_Name":"Justin"},
 {"Class_ID":605, "Days":"Saturday", "Class_Cost":20, "Location":"Great Hall", "Sports_Name":"Pilates", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":33, "A_Name":"Susan"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":1, "A_Name":"Katie"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":2, "A_Name":"Fred"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":6, "A_Name":"Luna"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":7, "A_Name":"Charlie"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":8, "A_Name":"Penelope"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":9, "A_Name":"Ginny"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":11, "A_Name":"Harry"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":15, "A_Name":"Dean"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":17, "A_Name":"Seamus"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":19, "A_Name":"Cho"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":21, "A_Name":"Neville"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":22, "A_Name":"Draco"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":23, "A_Name":"Ron"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":24, "A_Name":"Percy"},
 {"Class_ID":606, "Days":"Sunday", "Class_Cost":9, "Location":"Quidditch Pitch", "Sports_Name":"Yoga", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":88, "I_Name":"Flitwick", "A_HOGID":26, "A_Name":"George"},
 {"Class_ID":607, "Days":"Monday", "Class_Cost":5, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":9, "A_Name":"Ginny"},
 {"Class_ID":607, "Days":"Monday", "Class_Cost":5, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":20, "A_Name":"Hermione"},
 {"Class_ID":607, "Days":"Monday", "Class_Cost":5, "Location":"Quidditch Pitch", "Sports_Name":"Quidditch", "Class_Start_Time":"08:00:00", "Class_End_Time":"09:00:00", "I_HOGID":92, "I_Name":"Dumbledore", "A_HOGID":41, "A_Name":"Godric"}]
)
db.game.insertMany(
[{"Team_ID_Home":201, "Team_Name_Home":"GRYFFINDOR", "Team_ID_Away":202, "Team_Name_Away":"Ravenclaw", "Game_No":1, "Tourn_ID":300, "Score_team_home":200, "Score_team_away":10, "Sport":"Quidditch"},
 {"Team_ID_Home":203, "Team_Name_Home":"Hufflepuff", "Team_ID_Away":204, "Team_Name_Away":"Slytherin", "Game_No":2, "Tourn_ID":300, "Score_team_home":10, "Score_team_away":200, "Sport":"Quidditch"},
 {"Team_ID_Home":201, "Team_Name_Home":"GRYFFINDOR", "Team_ID_Away":204, "Team_Name_Away":"Slytherin", "Game_No":3, "Tourn_ID":300, "Score_team_home":200, "Score_team_away":10, "Sport":"Quidditch"},
 {"Team_ID_Home":201, "Team_Name_Home":"GRYFFINDOR", "Team_ID_Away":203, "Team_Name_Away":"Hufflepuff", "Game_No":1, "Tourn_ID":301, "Score_team_home":400, "Score_team_away":20, "Sport":"Quidditch"},
 {"Team_ID_Home":202, "Team_Name_Home":"Ravenclaw", "Team_ID_Away":204, "Team_Name_Away":"Slytherin", "Game_No":2, "Tourn_ID":301, "Score_team_home":80, "Score_team_away":159, "Sport":"Quidditch"},
 {"Team_ID_Home":201, "Team_Name_Home":"GRYFFINDOR", "Team_ID_Away":204, "Team_Name_Away":"Slytherin", "Game_No":3, "Tourn_ID":301, "Score_team_home":200, "Score_team_away":201, "Sport":"Quidditch"},
 {"Team_ID_Home":201, "Team_Name_Home":"GRYFFINDOR", "Team_ID_Away":204, "Team_Name_Away":"Slytherin", "Game_No":1, "Tourn_ID":302, "Score_team_home":200, "Score_team_away":199, "Sport":"Quidditch"},
 {"Team_ID_Home":202, "Team_Name_Home":"Ravenclaw", "Team_ID_Away":203, "Team_Name_Away":"Hufflepuff", "Game_No":2, "Tourn_ID":302, "Score_team_home":200, "Score_team_away":180, "Sport":"Quidditch"},
 {"Team_ID_Home":201, "Team_Name_Home":"GRYFFINDOR", "Team_ID_Away":202, "Team_Name_Away":"Ravenclaw", "Game_No":3, "Tourn_ID":302, "Score_team_home":200, "Score_team_away":190, "Sport":"Quidditch"},
 {"Team_ID_Home":207, "Team_Name_Home":"Girls Rule", "Team_ID_Away":209, "Team_Name_Away":"Lightning Strikes", "Game_No":1, "Tourn_ID":303, "Score_team_home":88, "Score_team_away":17, "Sport":"Basketball"},
 {"Team_ID_Home":208, "Team_Name_Home":"Weasleys", "Team_ID_Away":211, "Team_Name_Away":"Draco Fan Club", "Game_No":2, "Tourn_ID":303, "Score_team_home":30, "Score_team_away":18, "Sport":"Basketball"},
 {"Team_ID_Home":207, "Team_Name_Home":"Girls Rule", "Team_ID_Away":208, "Team_Name_Away":"Weasleys", "Game_No":3, "Tourn_ID":303, "Score_team_home":100, "Score_team_away":10, "Sport":"Basketball"},
 {"Team_ID_Home":209, "Team_Name_Home":"Lightning Strikes", "Team_ID_Away":211, "Team_Name_Away":"Draco Fan Club", "Game_No":1, "Tourn_ID":304, "Score_team_home":40, "Score_team_away":19, "Sport":"Hockey"},
 {"Team_ID_Home":210, "Team_Name_Home":"The Chudley Cannons", "Team_ID_Away":211, "Team_Name_Away":"Draco Fan Club", "Game_No":1, "Tourn_ID":305, "Score_team_home":3, "Score_team_away":2, "Sport":"Hockey"},
 {"Team_ID_Home":215, "Team_Name_Home":"Twinning", "Team_ID_Away":212, "Team_Name_Away":"Smarties", "Game_No":1, "Tourn_ID":306, "Score_team_home":14, "Score_team_away":10, "Sport":"Tennis"},
 {"Team_ID_Home":214, "Team_Name_Home":"Do I Have To Play", "Team_ID_Away":216, "Team_Name_Away":"Dumbledore's Army", "Game_No":2, "Tourn_ID":306, "Score_team_home":14, "Score_team_away":10, "Sport":"Tennis"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":217, "Team_Name_Away":"Forge", "Game_No":3, "Tourn_ID":306, "Score_team_home":14, "Score_team_away":10, "Sport":"Tennis"},
 {"Team_ID_Home":220, "Team_Name_Home":"Terrible Twos", "Team_ID_Away":218, "Team_Name_Away":"Not Hogwarts", "Game_No":4, "Tourn_ID":306, "Score_team_home":14, "Score_team_away":10, "Sport":"Tennis"},
 {"Team_ID_Home":220, "Team_Name_Home":"Terrible Twos", "Team_ID_Away":215, "Team_Name_Away":"Twinning", "Game_No":5, "Tourn_ID":306, "Score_team_home":14, "Score_team_away":10, "Sport":"Tennis"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":214, "Team_Name_Away":"Do I Have To Play", "Game_No":6, "Tourn_ID":306, "Score_team_home":14, "Score_team_away":10, "Sport":"Tennis"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":220, "Team_Name_Away":"Terrible Twos", "Game_No":7, "Tourn_ID":306, "Score_team_home":14, "Score_team_away":10, "Sport":"Tennis"},
 {"Team_ID_Home":215, "Team_Name_Home":"Twinning", "Team_ID_Away":212, "Team_Name_Away":"Smarties", "Game_No":1, "Tourn_ID":307, "Score_team_home":9, "Score_team_away":8, "Sport":"Tennis"},
 {"Team_ID_Home":214, "Team_Name_Home":"Do I Have To Play", "Team_ID_Away":216, "Team_Name_Away":"Dumbledore's Army", "Game_No":2, "Tourn_ID":307, "Score_team_home":9, "Score_team_away":8, "Sport":"Tennis"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":217, "Team_Name_Away":"Forge", "Game_No":3, "Tourn_ID":307, "Score_team_home":9, "Score_team_away":8, "Sport":"Tennis"},
 {"Team_ID_Home":220, "Team_Name_Home":"Terrible Twos", "Team_ID_Away":218, "Team_Name_Away":"Not Hogwarts", "Game_No":4, "Tourn_ID":307, "Score_team_home":9, "Score_team_away":8, "Sport":"Tennis"},
 {"Team_ID_Home":220, "Team_Name_Home":"Terrible Twos", "Team_ID_Away":215, "Team_Name_Away":"Twinning", "Game_No":5, "Tourn_ID":307, "Score_team_home":9, "Score_team_away":8, "Sport":"Tennis"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":214, "Team_Name_Away":"Do I Have To Play", "Game_No":6, "Tourn_ID":307, "Score_team_home":9, "Score_team_away":8, "Sport":"Tennis"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":220, "Team_Name_Away":"Terrible Twos", "Game_No":7, "Tourn_ID":307, "Score_team_home":9, "Score_team_away":8, "Sport":"Tennis"},
 {"Team_ID_Home":217, "Team_Name_Home":"Forge", "Team_ID_Away":219, "Team_Name_Away":"Dream Team", "Game_No":1, "Tourn_ID":308, "Score_team_home":21, "Score_team_away":10, "Sport":"Ping Pong"},
 {"Team_ID_Home":214, "Team_Name_Home":"Do I Have To Play", "Team_ID_Away":220, "Team_Name_Away":"Terrible Twos", "Game_No":2, "Tourn_ID":308, "Score_team_home":21, "Score_team_away":11, "Sport":"Ping Pong"},
 {"Team_ID_Home":217, "Team_Name_Home":"Forge", "Team_ID_Away":214, "Team_Name_Away":"Do I Have To Play", "Game_No":3, "Tourn_ID":308, "Score_team_home":21, "Score_team_away":19, "Sport":"Ping Pong"},
 {"Team_ID_Home":214, "Team_Name_Home":"Do I Have To Play", "Team_ID_Away":216, "Team_Name_Away":"Dumbledore's Army", "Game_No":1, "Tourn_ID":309, "Score_team_home":21, "Score_team_away":19, "Sport":"Ping Pong"},
 {"Team_ID_Home":215, "Team_Name_Home":"Twinning", "Team_ID_Away":216, "Team_Name_Away":"Dumbledore's Army", "Game_No":2, "Tourn_ID":309, "Score_team_home":21, "Score_team_away":17, "Sport":"Ping Pong"},
 {"Team_ID_Home":215, "Team_Name_Home":"Twinning", "Team_ID_Away":214, "Team_Name_Away":"Do I Have To Play", "Game_No":3, "Tourn_ID":309, "Score_team_home":21, "Score_team_away":17, "Sport":"Ping Pong"},
 {"Team_ID_Home":220, "Team_Name_Home":"Terrible Twos", "Team_ID_Away":216, "Team_Name_Away":"Dumbledore's Army", "Game_No":1, "Tourn_ID":310, "Score_team_home":17, "Score_team_away":4, "Sport":"Volleyball"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":212, "Team_Name_Away":"Smarties", "Game_No":2, "Tourn_ID":310, "Score_team_home":17, "Score_team_away":8, "Sport":"Volleyball"},
 {"Team_ID_Home":213, "Team_Name_Home":"The Chosen Wons", "Team_ID_Away":220, "Team_Name_Away":"Terrible Twos", "Game_No":3, "Tourn_ID":310, "Score_team_home":17, "Score_team_away":10, "Sport":"Volleyball"}]
)
db.plays_for.insertMany(
[{"P_HOGID":1, "P_Name":"Katie", "Team_ID":201, "Team_Name":"GRYFFINDOR", "Type":"Player"},
 {"P_HOGID":2, "P_Name":"Fred", "Team_ID":201, "Team_Name":"GRYFFINDOR", "Type":"Player"},
 {"P_HOGID":9, "P_Name":"Ginny", "Team_ID":201, "Team_Name":"GRYFFINDOR", "Type":"Player"},
 {"P_HOGID":11, "P_Name":"Harry", "Team_ID":201, "Team_Name":"GRYFFINDOR", "Type":"Player"},
 {"P_HOGID":16, "P_Name":"Angelina", "Team_ID":201, "Team_Name":"GRYFFINDOR", "Type":"Player"},
 {"P_HOGID":26, "P_Name":"George", "Team_ID":201, "Team_Name":"GRYFFINDOR", "Type":"Player"},
 {"P_HOGID":41, "P_Name":"Godric", "Team_ID":201, "Team_Name":"GRYFFINDOR", "Type":"Captain"},
 {"P_HOGID":3, "P_Name":"Fleur", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Player"},
 {"P_HOGID":6, "P_Name":"Luna", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Player"},
 {"P_HOGID":8, "P_Name":"Penelope", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Player"},
 {"P_HOGID":14, "P_Name":"Viktor", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Player"},
 {"P_HOGID":19, "P_Name":"Cho", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Player"},
 {"P_HOGID":28, "P_Name":"Padma", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Player"},
 {"P_HOGID":29, "P_Name":"Michael", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Player"},
 {"P_HOGID":39, "P_Name":"Rowena", "Team_ID":202, "Team_Name":"Ravenclaw", "Type":"Captain"},
 {"P_HOGID":24, "P_Name":"Percy", "Team_ID":203, "Team_Name":"Hufflepuff", "Type":"Player"},
 {"P_HOGID":27, "P_Name":"Cedric", "Team_ID":203, "Team_Name":"Hufflepuff", "Type":"Player"},
 {"P_HOGID":30, "P_Name":"Ernie", "Team_ID":203, "Team_Name":"Hufflepuff", "Type":"Player"},
 {"P_HOGID":31, "P_Name":"Hannah", "Team_ID":203, "Team_Name":"Hufflepuff", "Type":"Player"},
 {"P_HOGID":32, "P_Name":"Justin", "Team_ID":203, "Team_Name":"Hufflepuff", "Type":"Player"},
 {"P_HOGID":33, "P_Name":"Susan", "Team_ID":203, "Team_Name":"Hufflepuff", "Type":"Player"},
 {"P_HOGID":40, "P_Name":"Helga", "Team_ID":203, "Team_Name":"Hufflepuff", "Type":"Captain"},
 {"P_HOGID":5, "P_Name":"Goyle", "Team_ID":204, "Team_Name":"Slytherin", "Type":"Player"},
 {"P_HOGID":13, "P_Name":"Crabbe", "Team_ID":204, "Team_Name":"Slytherin", "Type":"Player"},
 {"P_HOGID":22, "P_Name":"Draco", "Team_ID":204, "Team_Name":"Slytherin", "Type":"Player"},
 {"P_HOGID":34, "P_Name":"Pansy", "Team_ID":204, "Team_Name":"Slytherin", "Type":"Player"},
 {"P_HOGID":35, "P_Name":"Blaise", "Team_ID":204, "Team_Name":"Slytherin", "Type":"Player"},
 {"P_HOGID":36, "P_Name":"Marcus", "Team_ID":204, "Team_Name":"Slytherin", "Type":"Player"},
 {"P_HOGID":38, "P_Name":"Salazar", "Team_ID":204, "Team_Name":"Slytherin", "Type":"Captain"},
 {"P_HOGID":1, "P_Name":"Katie", "Team_ID":207, "Team_Name":"Girls Rule", "Type":"Player"},
 {"P_HOGID":16, "P_Name":"Angelina", "Team_ID":207, "Team_Name":"Girls Rule", "Type":"Player"},
 {"P_HOGID":19, "P_Name":"Cho", "Team_ID":207, "Team_Name":"Girls Rule", "Type":"Captain"},
 {"P_HOGID":28, "P_Name":"Padma", "Team_ID":207, "Team_Name":"Girls Rule", "Type":"Player"},
 {"P_HOGID":33, "P_Name":"Susan", "Team_ID":207, "Team_Name":"Girls Rule", "Type":"Player"},
 {"P_HOGID":2, "P_Name":"Fred", "Team_ID":208, "Team_Name":"Weasleys", "Type":"Captain"},
 {"P_HOGID":9, "P_Name":"Ginny", "Team_ID":208, "Team_Name":"Weasleys", "Type":"Player"},
 {"P_HOGID":10, "P_Name":"Bill", "Team_ID":208, "Team_Name":"Weasleys", "Type":"Player"},
 {"P_HOGID":24, "P_Name":"Percy", "Team_ID":208, "Team_Name":"Weasleys", "Type":"Player"},
 {"P_HOGID":26, "P_Name":"George", "Team_ID":208, "Team_Name":"Weasleys", "Type":"Player"},
 {"P_HOGID":11, "P_Name":"Harry", "Team_ID":209, "Team_Name":"Lightning Strikes", "Type":"Captain"},
 {"P_HOGID":20, "P_Name":"Hermione", "Team_ID":209, "Team_Name":"Lightning Strikes", "Type":"Player"},
 {"P_HOGID":21, "P_Name":"Neville", "Team_ID":209, "Team_Name":"Lightning Strikes", "Type":"Player"},
 {"P_HOGID":23, "P_Name":"Ron", "Team_ID":209, "Team_Name":"Lightning Strikes", "Type":"Player"},
 {"P_HOGID":31, "P_Name":"Hannah", "Team_ID":209, "Team_Name":"Lightning Strikes", "Type":"Player"},
 {"P_HOGID":8, "P_Name":"Penelope", "Team_ID":210, "Team_Name":"The Chudley Cannons", "Type":"Player"},
 {"P_HOGID":14, "P_Name":"Viktor", "Team_ID":210, "Team_Name":"The Chudley Cannons", "Type":"Captain"},
 {"P_HOGID":24, "P_Name":"Percy", "Team_ID":210, "Team_Name":"The Chudley Cannons", "Type":"Player"},
 {"P_HOGID":25, "P_Name":"Lavender", "Team_ID":210, "Team_Name":"The Chudley Cannons", "Type":"Player"},
 {"P_HOGID":31, "P_Name":"Hannah", "Team_ID":210, "Team_Name":"The Chudley Cannons", "Type":"Player"},
 {"P_HOGID":5, "P_Name":"Goyle", "Team_ID":211, "Team_Name":"Draco Fan Club", "Type":"Player"},
 {"P_HOGID":13, "P_Name":"Crabbe", "Team_ID":211, "Team_Name":"Draco Fan Club", "Type":"Player"},
 {"P_HOGID":22, "P_Name":"Draco", "Team_ID":211, "Team_Name":"Draco Fan Club", "Type":"Captain"},
 {"P_HOGID":34, "P_Name":"Pansy", "Team_ID":211, "Team_Name":"Draco Fan Club", "Type":"Player"},
 {"P_HOGID":35, "P_Name":"Blaise", "Team_ID":211, "Team_Name":"Draco Fan Club", "Type":"Player"},
 {"P_HOGID":6, "P_Name":"Luna", "Team_ID":212, "Team_Name":"Smarties", "Type":"Player"},
 {"P_HOGID":20, "P_Name":"Hermione", "Team_ID":212, "Team_Name":"Smarties", "Type":"Captain"},
 {"P_HOGID":11, "P_Name":"Harry", "Team_ID":213, "Team_Name":"The Chosen Wons", "Type":"Captain"},
 {"P_HOGID":23, "P_Name":"Ron", "Team_ID":213, "Team_Name":"The Chosen Wons", "Type":"Player"},
 {"P_HOGID":8, "P_Name":"Penelope", "Team_ID":214, "Team_Name":"Do I Have To Play", "Type":"Captain"},
 {"P_HOGID":24, "P_Name":"Percy", "Team_ID":214, "Team_Name":"Do I Have To Play", "Type":"Player"},
 {"P_HOGID":18, "P_Name":"Pavarti", "Team_ID":215, "Team_Name":"Twinning", "Type":"Captain"},
 {"P_HOGID":28, "P_Name":"Padma", "Team_ID":215, "Team_Name":"Twinning", "Type":"Player"},
 {"P_HOGID":6, "P_Name":"Luna", "Team_ID":216, "Team_Name":"Dumbledore's Army", "Type":"Player"},
 {"P_HOGID":21, "P_Name":"Neville", "Team_ID":216, "Team_Name":"Dumbledore's Army", "Type":"Captain"},
 {"P_HOGID":2, "P_Name":"Fred", "Team_ID":217, "Team_Name":"Forge", "Type":"Captain"},
 {"P_HOGID":26, "P_Name":"George", "Team_ID":217, "Team_Name":"Forge", "Type":"Player"},
 {"P_HOGID":3, "P_Name":"Fleur", "Team_ID":218, "Team_Name":"Not Hogwarts", "Type":"Captain"},
 {"P_HOGID":14, "P_Name":"Viktor", "Team_ID":218, "Team_Name":"Not Hogwarts", "Type":"Player"},
 {"P_HOGID":15, "P_Name":"Dean", "Team_ID":219, "Team_Name":"Dream Team", "Type":"Captain"},
 {"P_HOGID":17, "P_Name":"Seamus", "Team_ID":219, "Team_Name":"Dream Team", "Type":"Player"},
 {"P_HOGID":13, "P_Name":"Crabbe", "Team_ID":220, "Team_Name":"Terrible Twos", "Type":"Player"},
 {"P_HOGID":22, "P_Name":"Draco", "Team_ID":220, "Team_Name":"Terrible Twos", "Type":"Captain"}]
)
db.tournament_registration.insertMany(
[{"Tourn_ID":300, "Sport":"Quidditch", "Price":140, "Team_ID":201, "Team_Name":"GRYFFINDOR", "C_HOGID":41, "C_Name":"Godric"},
 {"Tourn_ID":300, "Sport":"Quidditch", "Price":140, "Team_ID":202, "Team_Name":"Ravenclaw", "C_HOGID":39, "C_Name":"Rowena"},
 {"Tourn_ID":300, "Sport":"Quidditch", "Price":140, "Team_ID":203, "Team_Name":"Hufflepuff", "C_HOGID":40, "C_Name":"Helga"},
 {"Tourn_ID":300, "Sport":"Quidditch", "Price":140, "Team_ID":204, "Team_Name":"Slytherin", "C_HOGID":38, "C_Name":"Salazar"},
 {"Tourn_ID":301, "Sport":"Quidditch", "Price":140, "Team_ID":201, "Team_Name":"GRYFFINDOR", "C_HOGID":41, "C_Name":"Godric"},
 {"Tourn_ID":301, "Sport":"Quidditch", "Price":140, "Team_ID":202, "Team_Name":"Ravenclaw", "C_HOGID":39, "C_Name":"Rowena"},
 {"Tourn_ID":301, "Sport":"Quidditch", "Price":140, "Team_ID":203, "Team_Name":"Hufflepuff", "C_HOGID":40, "C_Name":"Helga"},
 {"Tourn_ID":301, "Sport":"Quidditch", "Price":140, "Team_ID":204, "Team_Name":"Slytherin", "C_HOGID":38, "C_Name":"Salazar"},
 {"Tourn_ID":302, "Sport":"Quidditch", "Price":140, "Team_ID":201, "Team_Name":"GRYFFINDOR", "C_HOGID":41, "C_Name":"Godric"},
 {"Tourn_ID":302, "Sport":"Quidditch", "Price":140, "Team_ID":202, "Team_Name":"Ravenclaw", "C_HOGID":39, "C_Name":"Rowena"},
 {"Tourn_ID":302, "Sport":"Quidditch", "Price":140, "Team_ID":203, "Team_Name":"Hufflepuff", "C_HOGID":40, "C_Name":"Helga"},
 {"Tourn_ID":302, "Sport":"Quidditch", "Price":140, "Team_ID":204, "Team_Name":"Slytherin", "C_HOGID":38, "C_Name":"Salazar"},
 {"Tourn_ID":303, "Sport":"Basketball", "Price":40, "Team_ID":207, "Team_Name":"Girls Rule", "C_HOGID":19, "C_Name":"Cho"},
 {"Tourn_ID":303, "Sport":"Basketball", "Price":40, "Team_ID":208, "Team_Name":"Weasleys", "C_HOGID":2, "C_Name":"Fred"},
 {"Tourn_ID":303, "Sport":"Basketball", "Price":40, "Team_ID":209, "Team_Name":"Lightning Strikes", "C_HOGID":11, "C_Name":"Harry"},
 {"Tourn_ID":303, "Sport":"Basketball", "Price":40, "Team_ID":211, "Team_Name":"Draco Fan Club", "C_HOGID":22, "C_Name":"Draco"},
 {"Tourn_ID":304, "Sport":"Hockey", "Price":40, "Team_ID":209, "Team_Name":"Lightning Strikes", "C_HOGID":11, "C_Name":"Harry"},
 {"Tourn_ID":304, "Sport":"Hockey", "Price":40, "Team_ID":211, "Team_Name":"Draco Fan Club", "C_HOGID":22, "C_Name":"Draco"},
 {"Tourn_ID":305, "Sport":"Hockey", "Price":40, "Team_ID":209, "Team_Name":"Lightning Strikes", "C_HOGID":11, "C_Name":"Harry"},
 {"Tourn_ID":305, "Sport":"Hockey", "Price":40, "Team_ID":210, "Team_Name":"The Chudley Cannons", "C_HOGID":14, "C_Name":"Viktor"},
 {"Tourn_ID":305, "Sport":"Hockey", "Price":40, "Team_ID":211, "Team_Name":"Draco Fan Club", "C_HOGID":22, "C_Name":"Draco"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":212, "Team_Name":"Smarties", "C_HOGID":20, "C_Name":"Hermione"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":213, "Team_Name":"The Chosen Wons", "C_HOGID":11, "C_Name":"Harry"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":214, "Team_Name":"Do I Have To Play", "C_HOGID":8, "C_Name":"Penelope"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":215, "Team_Name":"Twinning", "C_HOGID":18, "C_Name":"Pavarti"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":216, "Team_Name":"Dumbledore's Army", "C_HOGID":21, "C_Name":"Neville"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":217, "Team_Name":"Forge", "C_HOGID":2, "C_Name":"Fred"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":218, "Team_Name":"Not Hogwarts", "C_HOGID":3, "C_Name":"Fleur"},
 {"Tourn_ID":306, "Sport":"Tennis", "Price":30, "Team_ID":220, "Team_Name":"Terrible Twos", "C_HOGID":22, "C_Name":"Draco"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":212, "Team_Name":"Smarties", "C_HOGID":20, "C_Name":"Hermione"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":213, "Team_Name":"The Chosen Wons", "C_HOGID":11, "C_Name":"Harry"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":214, "Team_Name":"Do I Have To Play", "C_HOGID":8, "C_Name":"Penelope"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":215, "Team_Name":"Twinning", "C_HOGID":18, "C_Name":"Pavarti"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":216, "Team_Name":"Dumbledore's Army", "C_HOGID":21, "C_Name":"Neville"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":217, "Team_Name":"Forge", "C_HOGID":2, "C_Name":"Fred"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":218, "Team_Name":"Not Hogwarts", "C_HOGID":3, "C_Name":"Fleur"},
 {"Tourn_ID":307, "Sport":"Tennis", "Price":30, "Team_ID":220, "Team_Name":"Terrible Twos", "C_HOGID":22, "C_Name":"Draco"},
 {"Tourn_ID":308, "Sport":"Ping Pong", "Price":40, "Team_ID":214, "Team_Name":"Do I Have To Play", "C_HOGID":8, "C_Name":"Penelope"},
 {"Tourn_ID":308, "Sport":"Ping Pong", "Price":40, "Team_ID":217, "Team_Name":"Forge", "C_HOGID":2, "C_Name":"Fred"},
 {"Tourn_ID":308, "Sport":"Ping Pong", "Price":40, "Team_ID":219, "Team_Name":"Dream Team", "C_HOGID":15, "C_Name":"Dean"},
 {"Tourn_ID":308, "Sport":"Ping Pong", "Price":40, "Team_ID":220, "Team_Name":"Terrible Twos", "C_HOGID":22, "C_Name":"Draco"},
 {"Tourn_ID":309, "Sport":"Ping Pong", "Price":40, "Team_ID":214, "Team_Name":"Do I Have To Play", "C_HOGID":8, "C_Name":"Penelope"},
 {"Tourn_ID":309, "Sport":"Ping Pong", "Price":40, "Team_ID":215, "Team_Name":"Twinning", "C_HOGID":18, "C_Name":"Pavarti"},
 {"Tourn_ID":309, "Sport":"Ping Pong", "Price":40, "Team_ID":216, "Team_Name":"Dumbledore's Army", "C_HOGID":21, "C_Name":"Neville"},
 {"Tourn_ID":310, "Sport":"Volleyball", "Price":30, "Team_ID":212, "Team_Name":"Smarties", "C_HOGID":20, "C_Name":"Hermione"},
 {"Tourn_ID":310, "Sport":"Volleyball", "Price":30, "Team_ID":213, "Team_Name":"The Chosen Wons", "C_HOGID":11, "C_Name":"Harry"},
 {"Tourn_ID":310, "Sport":"Volleyball", "Price":30, "Team_ID":216, "Team_Name":"Dumbledore's Army", "C_HOGID":21, "C_Name":"Neville"},
 {"Tourn_ID":310, "Sport":"Volleyball", "Price":30, "Team_ID":220, "Team_Name":"Terrible Twos", "C_HOGID":22, "C_Name":"Draco"}]
)
db.tournament_workers.insertMany(
[{"Tourn_ID":300, "W_Name":"Hooch", "W_HOGID":90},
 {"Tourn_ID":300, "W_Name":"McGonnagall", "W_HOGID":91},
 {"Tourn_ID":300, "W_Name":"Sprout", "W_HOGID":93},
 {"Tourn_ID":301, "W_Name":"Flitwick", "W_HOGID":88},
 {"Tourn_ID":301, "W_Name":"Moody", "W_HOGID":89},
 {"Tourn_ID":301, "W_Name":"Hooch", "W_HOGID":90},
 {"Tourn_ID":302, "W_Name":"Hooch", "W_HOGID":90},
 {"Tourn_ID":302, "W_Name":"Snape", "W_HOGID":97},
 {"Tourn_ID":303, "W_Name":"McGonnagall", "W_HOGID":91},
 {"Tourn_ID":304, "W_Name":"Moody", "W_HOGID":89},
 {"Tourn_ID":305, "W_Name":"Quirrel/He Who Must Not Be Named", "W_HOGID":96},
 {"Tourn_ID":306, "W_Name":"Umbridge", "W_HOGID":95},
 {"Tourn_ID":307, "W_Name":"Hooch", "W_HOGID":90},
 {"Tourn_ID":308, "W_Name":"Flitwick", "W_HOGID":88},
 {"Tourn_ID":309, "W_Name":"Snape", "W_HOGID":97},
 {"Tourn_ID":310, "W_Name":"Dumbledore", "W_HOGID":92}]
)
db.users.insertMany([{"HOGID":1, "Name":"Katie", "Type":"Player"},
 {"HOGID":2, "Name":"Fred", "Type":"Player"},
 {"HOGID":3, "Name":"Fleur", "Type":"Player"},
 {"HOGID":5, "Name":"Goyle", "Type":"Player"},
 {"HOGID":6, "Name":"Luna", "Type":"Player"},
 {"HOGID":7, "Name":"Charlie", "Type":"Player"},
 {"HOGID":8, "Name":"Penelope", "Type":"Player"},
 {"HOGID":9, "Name":"Ginny", "Type":"Player"},
 {"HOGID":10, "Name":"Bill", "Type":"Player"},
 {"HOGID":11, "Name":"Harry", "Type":"Player"},
 {"HOGID":12, "Name":"Dudley", "Type":"Player"},
 {"HOGID":13, "Name":"Crabbe", "Type":"Player"},
 {"HOGID":14, "Name":"Viktor", "Type":"Player"},
 {"HOGID":15, "Name":"Dean", "Type":"Player"},
 {"HOGID":16, "Name":"Angelina", "Type":"Player"},
 {"HOGID":17, "Name":"Seamus", "Type":"Player"},
 {"HOGID":18, "Name":"Pavarti", "Type":"Player"},
 {"HOGID":19, "Name":"Cho", "Type":"Player"},
 {"HOGID":20, "Name":"Hermione", "Type":"Player"},
 {"HOGID":21, "Name":"Neville", "Type":"Player"},
 {"HOGID":22, "Name":"Draco", "Type":"Player"},
 {"HOGID":23, "Name":"Ron", "Type":"Player"},
 {"HOGID":24, "Name":"Percy", "Type":"Player"},
 {"HOGID":25, "Name":"Lavender", "Type":"Player"},
 {"HOGID":26, "Name":"George", "Type":"Player"},
 {"HOGID":27, "Name":"Cedric", "Type":"Player"},
 {"HOGID":28, "Name":"Padma", "Type":"Player"},
 {"HOGID":29, "Name":"Michael", "Type":"Player"},
 {"HOGID":30, "Name":"Ernie", "Type":"Player"},
 {"HOGID":31, "Name":"Hannah", "Type":"Player"},
 {"HOGID":32, "Name":"Justin", "Type":"Player"},
 {"HOGID":33, "Name":"Susan", "Type":"Player"},
 {"HOGID":34, "Name":"Pansy", "Type":"Player"},
 {"HOGID":35, "Name":"Blaise", "Type":"Player"},
 {"HOGID":36, "Name":"Marcus", "Type":"Player"},
 {"HOGID":37, "Name":"Millicent", "Type":"Player"},
 {"HOGID":38, "Name":"Salazar", "Type":"Player"},
 {"HOGID":39, "Name":"Rowena", "Type":"Player"},
 {"HOGID":40, "Name":"Helga", "Type":"Player"},
 {"HOGID":41, "Name":"Godric", "Type":"Player"},
 {"HOGID":88, "Name":"Flitwick", "Type":"Instructor"},
 {"HOGID":89, "Name":"Moody", "Type":"Instructor"},
 {"HOGID":90, "Name":"Hooch", "Type":"Instructor"},
 {"HOGID":91, "Name":"McGonnagall", "Type":"Instructor"},
 {"HOGID":92, "Name":"Dumbledore", "Type":"Instructor"},
 {"HOGID":93, "Name":"Sprout", "Type":"Instructor"},
 {"HOGID":94, "Name":"Lupin", "Type":"Instructor"},
 {"HOGID":95, "Name":"Umbridge", "Type":"Instructor"},
 {"HOGID":96, "Name":"Quirrel/He Who Must Not Be Named", "Type":"Instructor"},
 {"HOGID":97, "Name":"Snape", "Type":"Instructor"},
 {"HOGID":98, "Name":"Serius", "Type":"Instructor"},
 {"HOGID":99, "Name":"Lockhart", "Type":"Instructor"},
 {"HOGID":100, "Name":"Hagrid", "Type":"Instructor"}])
